server:
  port: 8082
  servlet:
    contextPath: /pinthouse
spring:
  datasource:
    password: "#Btrlh211299"
    url: jdbc:mysql://localhost:3306/pinthouse_db?user=root&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver